#
# A one-of task you can run on concourse to run a single maven test
#
# Run this with the following command from the ROOT of the sts4 repo:
#
#  fly -t tools execute -x --config concourse/tasks/run-manifest-yaml-test.yml
inputs:
- name: sts4
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  dir: sts4/vscode-extensions/vscode-manifest-yaml
  path: ../mvnw
  args: 
  - "-U"
  - "-f"
  - "../pom.xml"
  - "-pl"
  - "vscode-manifest-yaml"
  - "-am"
  - "-DfailIfNoTests=false"
  - "-Dtest=ManifestYamlEditorTest#reconcileShowsWarningOnUnknownService"
  - "clean"
  - "install"