inputs:
- name: sts4
- name: vsix-resource
outputs:
- name: sts4-out
- name: website
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kdvolder/sts4-build-env
run:
  path: sts4/concourse/tasks/vsce-publish.sh
